version: "3.3"
services:
  reactapp:
      build: .
      restart: always
      ports:
        - 8080:8080
      environment:
        - VIYA_SERVER=
        - CLIENTID=reactapp
        - CLIENTSECRET=secret
        - APPNAME=reactapp
        - APPPORT=8080
        - LOGLEVEL=error